pipeline {
	agent any

	tools {
		nodejs "nodejS"
	}

	stages {
		
		stage('Install Dependencies') {
			steps {
				dir('frontend/dksl') {
					sh 'pnpm install'
				}
			}
		}

		stage('React Build') {
			steps {
				dir('frontend/dksl') {
					sh 'pnpm install'
					sh 'pnpm dev'
				}
			}
		}

		stage('Docker Build') {
			steps {
				dir('frontend/dksl') {
					sh 'docker build -t dksl_front:latest .'
				}
			}
		}

		stage('Deploy') {
			steps{
				sh 'docker rm -f front'
				sh 'docker run -d --name front -p 3126:3126 -u root	dksl_front:latest'
				}
		}

		stage('Finish') {
			steps{
				sh 'docker images -qf dangling=true | xargs -I{} docker rmi {}'
			}
		}
	}
}